meta_product_name: "Hangover"
meta_title: "Hangover - Go out and have fun"
meta_description: "This is the best webapp to go out with your friends and have fun"
meta_image: "cover.png" # should exist in `app/assets/images/`
